convert:
	~/scoop/apps/libreoffice/current/LibreOffice/program/soffice.exe --headless --convert-to pdf final_slide.pptx --outdir .

run:
	python -m core_ai.libs.main
	~/scoop/apps/libreoffice/current/LibreOffice/program/soffice.exe --headless --convert-to pdf final_slide.pptx --outdir .
